name: Java CI with Maven

on:
  push:
    branches: [ "master" ]   # Run on pushes to main
  pull_request:
    branches: [ "master" ]   # Run on PRs targeting main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Build with Maven
      - name: Build with Maven
        run: mvn -B clean package

      # Run tests
      - name: Run tests
        run: mvn test

      # Upload artifact (your JAR)
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: spring-boot-app
          path: target/*.jar
